### ISSUE TITLE
Add Support for Batch Inference Processor Deployments.

### ISSUE THREAD

**Issue by ForeverAngry** [philschmid/terraform-aws-llm-sagemaker#4]
### Overview
It would be great if the module could allow for deployment of batch inference processing deployments.

### Motivation
The current Terraform module lacks a mechanism to configure batch processing capabilities. For users working with large data volumes or recurring batch jobs, such as those using AWS services like SageMaker, adding support for batch processing within the module will simplify and streamline infrastructure provisioning.

### Example Use Case
Be able to schedule nightly batch inference jobs on large datasets (100+ GB) stored in S3 using SageMaker.

**Comment by philschmid** [comment]
Not sure this makes sense to add as terraform features. As those kind of jobs are not directly related to infrastructure which you need to teardown again. I would suggest to take a look at this example: https://github.com/huggingface/notebooks/blob/main/sagemaker/12_batch_transform_inference/sagemaker-notebook.ipynb
and setup a cronjob.

**Comment by ForeverAngry** [comment]
thank you for the consideration and advice.  great package, btw!
